version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
    - 0.149.0
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: "@babel/plugin-transform-modules-commonjs"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: "@babel/preset-flow"
    versions:
    - 7.12.1
    - 7.12.13
  commit-message:
    prefix: chore
    include: scope
  registries:
  - npm-registry-registry-npmjs-org
